<ul>
  <li>
    <a href="default.aspx">Home</a>
  </li>
</ul>
<div class="leftcolumntitle"><b>Getting Started</b><br/></div>
<ul>
	<li><a href="default.aspx">Introduction</a></li>
	<li><a href="Requirements.aspx">Requirements</a></li>
</ul>

<div class="leftcolumntitle"><b>Signing In</b><br/></div>
<ul>
	<li><a href="Register.aspx">Register</a></li>
	<li><a href="loginout.aspx">Logging In/Out</a></li>
	<li><a href="Change-status.aspx">Change your status</a></li>
</ul>
<div class="leftcolumntitle"><b>Managing Contacts</b><br/></div>
<ul>
	<li><a href="contacts-list.aspx">About your contacts list</a></li>
	<li><a href="Add-contact.aspx">Add a contact</a></li>
	<li><a href="Block-contact.aspx">Block others from seeing or contacting you</a></li>
</ul>

<div class="leftcolumntitle"><b>Sending and Receiving Instant Messages</b><br/></div>
<ul>
	<li><a href="Sending-Messages.aspx">Send a message</a></li>
	<li><a href="Using-Smilies.aspx">Use emoticons</a></li>
	<li><a href="Text-Formatting.aspx">Text Formatting</a></li>
	<li><a href="sounds-alerts.aspx">Enable/Disable Sound</a></li>
	<li><a href="Save-conversation.aspx">Save a conversation</a></li>
	<li><a href="Invite-users.aspx">Invite others into a room</a></li>
	<li><a href="Clear-screen.aspx">Clear screen</a></li>
	<li><a href="Messenger-Commands.aspx">Messenger Commands</a></li>
	<li><a href="Auto-focus.aspx">Auto focus</a></li>
	<li><a href="Auto-Scroll.aspx">Auto Scroll</a></li>
	<li><a href="Chat-Acronyms.aspx">Chat Acronyms</a></li>
</ul>
