//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyUSC.MyTeams {
    
    
    public partial class PickUsername {
        
        /// <summary>
        /// TBSCLabel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyUSC.Classes.TBSCLabel TBSCLabel1;
        
        /// <summary>
        /// txtUsername control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyUSC.Classes.TBSCTextBox txtUsername;
        
        /// <summary>
        /// btnCheckName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyUSC.Classes.TBSCButton btnCheckName;
        
        /// <summary>
        /// lblNameAvailable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyUSC.Classes.TBSCLabel lblNameAvailable;
        
        /// <summary>
        /// lblNameTaken control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyUSC.Classes.TBSCLabel lblNameTaken;
        
        /// <summary>
        /// btnSuggest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyUSC.Classes.TBSCButton btnSuggest;
        
        /// <summary>
        /// TBSCLabel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyUSC.Classes.TBSCLabel TBSCLabel2;
        
        /// <summary>
        /// txtPassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyUSC.Classes.TBSCTextBox txtPassword;
        
        /// <summary>
        /// TBSCLabel3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyUSC.Classes.TBSCLabel TBSCLabel3;
        
        /// <summary>
        /// txtConfirmPswd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyUSC.Classes.TBSCTextBox txtConfirmPswd;
        
        /// <summary>
        /// btnOK control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyUSC.Classes.TBSCButton btnOK;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new MyUSC.USCMaster Master {
            get {
                return ((MyUSC.USCMaster)(base.Master));
            }
        }
    }
}
