<ul>
  <li>
    <a href="default.aspx">Home</a>
  </li>
</ul>
<div class="leftcolumntitle">
  <b>Getting Started</b>
</div>
<ul>
  <li>
    <a href="default.aspx">Introduction</a>
  </li>
  <li>
    <a href="Interface-overview.aspx">User Interface overview</a>
  </li>
  <li>
    <a href="Admin-Interface.aspx">Admin Interface</a>
  </li>
</ul>
<div class="leftcolumntitle"><b>Join a Chat</b><br/></div>
<ul>
	<li><a href="Register.aspx">Register</a></li>
  <li>
    <a href="loginout.aspx">Logging In/Out</a>
  </li>
  <li>
    <a href="participatechat.aspx">Entering Room</a>
  </li>
  <li>
    <a href="Poor-Connections.aspx">Poor Internet Connections</a>
  </li>
</ul>

<div class="leftcolumntitle">
  <b>Chatting </b>
  <br/>
</div>
<ul>
  <li>
    <a href="Sendingmessages.aspx">Sending messages</a>
  </li>
  <li>
    <a href="SendingMessagestouser.aspx">Sending messages to a user</a>
  </li>
  <li>
    <a href="Whisperchat.aspx">Whisper to other people</a>
  </li>
  <li>
    <a href="PrivateChat.aspx">Private Chat Window</a>
  </li>
  <li>
    <a href="Interval-between-utterances.aspx">Interval between utterances</a>
  </li>
  <li>
    <a href="Ignoring-Users.aspx">Ignoring Users</a>
  </li>
  <li>
    <a href="sounds-alerts.aspx">Enable/Disable Sound </a>
  </li>
  <li>
    <a href="Save-conversation.aspx">Save a conversation</a>
  </li>
  <li>
    <a href="Invite-users.aspx">Invite others into a room </a>
  </li>

	<li><a href="Clear-screen.aspx">Clear screen</a></li>
	<li><a href="View-profile.aspx">View user's profile </a></li>
	<li><a href="Change-Avatar.aspx">Changing Avatar</a></li>
	<li><a href="Using-Smilies.aspx">Using Smilies</a></li>
	<li><a href="Text-Formatting.aspx">Text Formatting</a></li>
	<li><a href="CuteChat-Commands.aspx">CuteChat Commands</a></li>
	<li><a href="Change-skin.aspx">Change the skin</a></li>
	<li><a href="Auto-focus.aspx">Auto focus</a></li>
	<li><a href="Auto-Scroll.aspx">Auto Scroll</a></li>
	<li><a href="Chat-Acronyms.aspx">Chat Acronyms</a></li>
</ul>


<div class="leftcolumntitle">
  <b>Moderated Chat Help</b>
</div>
<ul>
  <li>
    <a href="Moderated-Chat.aspx">What is Moderated Live Chat?
    </a>
  </li>
</ul>